# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'SLEDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SLEDemo
  pod 'SimpleLayoutEngine', :path => '../'

  target 'SLEDemoTests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'
  end

  target 'SLEDemoUITests' do
    # Pods for testing
  end

end
